# Generated by Django 4.1.3 on 2022-11-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=250)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriety.propriety')),
            ],
        ),
    ]
