# Generated by Django 4.1.3 on 2022-11-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='property_id',
            new_name='propriety',
        ),
    ]
