# Generated by Django 4.1.3 on 2022-11-26 20:20

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=booking.models.generate_random_code, editable=False, max_length=6, unique=True),
        ),
    ]
