# Generated by Django 4.1.3 on 2022-11-27 15:22

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='advertisement_id',
            new_name='advertisement',
        ),
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=booking.models.generate_booking_code, editable=False, max_length=6, unique=True),
        ),
    ]
