# Generated by Django 4.1.3 on 2022-11-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriety',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
