# Generated by Django 4.1.3 on 2022-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0002_alter_propriety_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriety',
            name='code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
