# Generated by Django 4.1.3 on 2022-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0003_alter_propriety_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriety',
            name='bathroom_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propriety',
            name='guests_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propriety',
            name='pet_frendly',
            field=models.BooleanField(default=False),
        ),
    ]
